server:
  port: 8080

spring:
  application:
    name: Tiny Url Service
  profiles:
    active: dev
  r2dbc:
    url: r2dbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?useSSL=false
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
